language: python

python:
  - 2.7

install:
  - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine
  - python setup.py install

script:
  - python setup.py check clean sdist nosetests

branches:
  only:
    - develop
    - master
